In [1]:
from scipy.spatial.distance import pdist
import numpy as np

In [4]:
a = np.random.rand(63,2)

In [6]:
p = pdist(a)

In [7]:
p_e = pdist(a, metric='euclidean')

In [8]:
p == p_e

array([ True,  True,  True, ...,  True,  True,  True])

In [9]:
p

array([0.61280688, 0.06717063, 1.14874135, ..., 0.7653452 , 0.25160602,
       0.51376227])

In [10]:
p_e

array([0.61280688, 0.06717063, 1.14874135, ..., 0.7653452 , 0.25160602,
       0.51376227])